const express = require("express");
const error = require("../middlewares/error");
const subjectRoute = require("../routes/subjectsRoute");
const roleRoute = require("../routes/roleRoute");
const authRoute = require("../routes/authRoute");
const statusRoute = require("../routes/statusRoute");
const userRoute = require("../routes/userRoute");
const classRoute = require("../routes/classRoute");
const sectionRoute = require("../routes/sectionRoute");
const academicYearRoute = require("../routes/academicYearRoute");
const parentRoute = require("../routes/parentRoute");
const teacherRoute = require("../routes/teacherRoute");
const institutionRoute = require("../routes/institutionRoute");
const driverRoute = require("../routes/driverRoute");
const vehicleRoute = require("../routes/vehicleRoute");
const vehicleTypeRoute = require("../routes/vehicleTypeRoute");
const shiftRoute = require("../routes/shiftRoute");
const periodRoute = require("../routes/periodRoute");
const timetableRoute = require("../routes/timetableRoute");
const noteRoute = require("../routes/noteRoute");
const assignmentRoute = require("../routes/assignmentRoute");
const taskRoute = require("../routes/taskRoute");
const termRoute = require("../routes/termRoute");
const assesmentRoute = require("../routes/assesmentRoute");
const examRoute = require("../routes/examRoute");
const studentAttendanceRoute = require("../routes/studentAttendanceRoute");
const newsFeedRoute = require("../routes/newsFeedRoute");
const studentRoute = require("../routes/studentRoute");
const eventRoute = require("../routes/eventRoute");
const departmentRoute = require("../routes/departmentRoute");
const jobTitleRoute = require("../routes/jobTitleRoute");
const leaveTypeRoute = require("../routes/leaveTypeRoute");
const leaveRoute = require("../routes/leaveRoute");
const employeeRoute = require("../routes/employeeRoute");

module.exports = (app) => {
  app.use(express.json());

  app.use("/api/subjects", subjectRoute);
  app.use("/api/roles", roleRoute);
  app.use("/api/auth", authRoute);
  app.use("/api/status", statusRoute);
  app.use("/api/users", userRoute);
  app.use("/api/classes", classRoute);
  app.use("/api/sections", sectionRoute);
  app.use("/api/academicYear", academicYearRoute);
  app.use("/api/parents", parentRoute);
  app.use("/api/teachers", teacherRoute);
  app.use("/api/institution", institutionRoute);
  app.use("/api/drivers", driverRoute);
  app.use("/api/vehicles", vehicleRoute);
  app.use("/api/vehicleType", vehicleTypeRoute);
  app.use("/api/shifts", shiftRoute);
  app.use("/api/periods", periodRoute);
  app.use("/api/timetable", timetableRoute);
  app.use("/api/notes", noteRoute);
  app.use("/api/assignments", assignmentRoute);
  app.use("/api/tasks", taskRoute);
  app.use("/api/terms", termRoute);
  app.use("/api/assesments", assesmentRoute);
  app.use("/api/exams", examRoute);
  app.use("/api/studentAttendance", studentAttendanceRoute);
  app.use("/api/newsfeed", newsFeedRoute);
  app.use("/api/studentAdmission", studentRoute);
  app.use("/api/events", eventRoute);
  app.use("/api/deparments", departmentRoute);
  app.use("/api/jobTitles", jobTitleRoute);
  app.use("/api/leaveTypes", leaveTypeRoute);
  app.use("/api/leaves", leaveRoute);
  app.use("/api/employees", employeeRoute);

  app.use(error);
};
